# Generated by Django 5.0.4 on 2024-04-30 12:59

import django_encrypted_filefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="document_file",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                upload_to="documents/W-2/"
            ),
        ),
    ]
